[project]
name = "video-to-text"
version = "0.1.0"
description = "Takes a video file, splits the audio and transcribes the text"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-openai>=1.1.7",
    "moviepy>=2.2.1",
    "openai>=2.15.0",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "ruff>=0.14.14",
]
