[project]
name = "video-to-text"
version = "0.2.0"
description = "Takes a video file, splits the audio and transcribes the text"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "moviepy>=2.2.1",
    "openai>=2.15.0",
]

[project.scripts]
vtt = "vtt.main:main"

[dependency-groups]
dev = [
    "coverage>=7.13.2",
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.14",
    "pre-commit>=3.4.0",
]
